### ISSUE TITLE
Add Problems and Concepts Section in README to list all the problems and concepts added in the repository.

### ISSUE THREAD

**Issue by vyasriday** [vyasriday/JS-Tidbits#15]
There should be a section in README which will have list of all the concepst and problems that have been added so far.

**Comment by yash-agarwal17** [comment]
Can I do this?

**Comment by vyasriday** [comment]
Sure @yash-agarwal17! 
Please add a Table of Contents Section at the end of README with the following format
```
### Table of Contents
	#### Concepts
	- [Concept Name][Link to File]: A short description if you can find one
	- and so on
    #### Problems
	- [Problem Name](Link to File): A short description	

```

Let me know if you need any help.

**Comment by Siddhant-K-code** [comment]
We Can do CP Problems of Leetcode or else using JavaScript.

**Comment by piratelicorne** [comment]
I can work on this, is still available?

**Comment by vyasriday** [comment]
@piratelicorne Yes. Please check the comments on PR as well.

**Comment by piratelicorne** [comment]
Hi @vyasriday I submitted it in the PR #29
