### ISSUE TITLE
Add star patten in JavaScript

### ISSUE THREAD

**Issue by vyasriday** [vyasriday/JS-Tidbits#16]
The program should print 
```
*
**
***
****
*****
```
and so on for a given value of `n`.

**Comment by yanagiragi** [comment]
Hey, may I try this PR?

**Comment by Reynadi531** [comment]
could i simplify your solution?

**Comment by karthikshetty03** [comment]
#18 
If above PR is not merged, than please consider this PR

**Comment by vyasriday** [comment]
I have merged @karthikshetty03  PR. And since there can be multiple ways to do something, you can just add you solution in the same file wit proper documented comments. @Reynadi531 @yanagiragi
