### ISSUE TITLE
 Add merge sort algorithm in javascript

### ISSUE THREAD

**Issue by vyasriday** [vyasriday/JS-Tidbits#5]
Add and implement merge sort algorithm in javascript.

**Comment by VolatianaYuliana** [comment]
Hey @vyasriday! Can I work on this and open the PR during Hacktoberfest? :)

**Comment by victormagalhaess** [comment]
Hey @VolatianaYuliana I'm sorry, I didn't saw your message and opened myself that PR :(

**Comment by VolatianaYuliana** [comment]
@victormagalhaess no worries :)

**Comment by vyasriday** [comment]
@victormagalhaess I have assigned this issue to you. @victormagalhaess You can work on others if you want or if you know of some problem statement or want to write about javascript concepts feel free to create the issue. :) Happy Coding

**Comment by Siddhant-K-code** [comment]
can I add more sorting & searching Algorithms in JavaScript ?

**Comment by vyasriday** [comment]
@Siddhant-K-code Yeah you can, Please check for any existing ones before adding yours.

**Comment by Siddhant-K-code** [comment]
sure, i will do it @vyasriday
