### ISSUE TITLE
Implement selection sort algorithm in javascript

### ISSUE THREAD

**Issue by vyasriday** [vyasriday/JS-Tidbits#8]

**Comment by surajat17** [comment]
i have been doing competitive programming for a while so i do have a good knowledge of selection sort but i am new to open source community can i wok on it?

**Comment by vyasriday** [comment]
Sure Assigning you. @surajat17. Feel free to add ⭐ to the repo.

**Comment by surajat17** [comment]
thanks i will complete this task within 2 days
